name: ETL Bitrix → Supabase

on:
  schedule:
    # roda todo dia de hora em hora às 5’— ajuste conforme necessidade
    - cron:  '5 * * * *'
  workflow_dispatch:  # permite também rodar manualmente na aba Actions

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configure Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar ETL incremental
        env:
          # Bitrix
          BITRIX_HASH_USER:    ${{ secrets.BITRIX_HASH_USER }}
          BITRIX_HASH_ACESSO:  ${{ secrets.BITRIX_HASH_ACESSO }}
          TOKEN_BI_CONNECTOR:  ${{ secrets.TOKEN_BI_CONNECTOR }}
          # Supabase
          SUPABASE_URL:        ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY:        ${{ secrets.SUPABASE_KEY }}
        run: |
          # Se o seu entrypoint for run_etl.py:
          python run_etl.py
